package com.instagram.filterkit.impl;

import X.AnonymousClass3Ox;
import X.AnonymousClass3UU;
import X.AnonymousClass3UV;
import X.AnonymousClass3UW;
import android.util.SparseArray;
import com.facebook.C0164R;
import com.facebook.react.views.progressbar.ReactProgressBarViewManager;
import com.fasterxml.jackson.core.base.ParserMinimalBase;
import java.util.Arrays;
import java.util.List;

public final class FilterFactoryImpl extends AnonymousClass3Ox {
    /* renamed from: B */
    public static final SparseArray f68317B = new SparseArray();

    /* renamed from: A */
    public final List m28303A() {
        return Arrays.asList(new Integer[]{Integer.valueOf(0), Integer.valueOf(643), Integer.valueOf(ParserMinimalBase.INT_r), Integer.valueOf(640), Integer.valueOf(706), Integer.valueOf(703), Integer.valueOf(705), Integer.valueOf(707), Integer.valueOf(709), Integer.valueOf(710), Integer.valueOf(702), Integer.valueOf(642)});
    }

    /* renamed from: B */
    public final AnonymousClass3UU m28304B(int i) {
        if (f68317B.size() == 0) {
            SparseArray sparseArray = f68317B;
            AnonymousClass3UV anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 0;
            String str = ReactProgressBarViewManager.DEFAULT_STYLE;
            anonymousClass3UV.f41623E = str;
            anonymousClass3UV.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV.f41626H = str;
            sparseArray.put(0, new AnonymousClass3UU(anonymousClass3UV));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 615;
            str = "Lark";
            anonymousClass3UV.f41623E = str;
            anonymousClass3UV.f41625G = C0164R.drawable.filter_lark;
            anonymousClass3UV.f41626H = str;
            str = "map";
            sparseArray.put(615, new AnonymousClass3UU(anonymousClass3UV.A(str, "lark/map.png")));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 614;
            anonymousClass3UV.f41623E = "Reyes";
            anonymousClass3UV.f41625G = C0164R.drawable.filter_reyes;
            anonymousClass3UV.f41626H = "StandardColorMap";
            sparseArray.put(614, new AnonymousClass3UU(anonymousClass3UV.A(str, "reyes/map.png")));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 613;
            anonymousClass3UV.f41623E = "Juno";
            anonymousClass3UV.f41625G = C0164R.drawable.filter_juno;
            anonymousClass3UV.f41626H = "StandardColorMap";
            sparseArray.put(613, new AnonymousClass3UU(anonymousClass3UV.A(str, "juno/map.png")));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 612;
            anonymousClass3UV.f41623E = "Aden";
            anonymousClass3UV.f41625G = C0164R.drawable.filter_aden;
            anonymousClass3UV.f41626H = "StandardColorMap";
            sparseArray.put(612, new AnonymousClass3UU(anonymousClass3UV.A(str, "aden/map.png")));
            AnonymousClass3UV anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 608;
            str = "Perpetua";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_perpetua;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(608, new AnonymousClass3UU(anonymousClass3UV2.A("map", "perpetua/map.png").A("overlay_map", "perpetua/overlay_map.png")));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 603;
            str = "Ludwig";
            anonymousClass3UV.f41623E = str;
            anonymousClass3UV.f41625G = C0164R.drawable.filter_ludwig;
            anonymousClass3UV.f41626H = str;
            sparseArray.put(603, new AnonymousClass3UU(anonymousClass3UV.A("map", "ludwig/map.png")));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 605;
            str = "Slumber";
            anonymousClass3UV.f41623E = str;
            anonymousClass3UV.f41625G = C0164R.drawable.filter_slumber;
            anonymousClass3UV.f41626H = str;
            str = "map";
            sparseArray.put(605, new AnonymousClass3UU(anonymousClass3UV.A(str, "slumber/map.png")));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 616;
            anonymousClass3UV.f41623E = "Crema";
            anonymousClass3UV.f41625G = C0164R.drawable.filter_crema;
            anonymousClass3UV.f41626H = "StandardColorMap";
            sparseArray.put(616, new AnonymousClass3UU(anonymousClass3UV.A(str, "crema/map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 24;
            str = "Amaro";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_amaro;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(24, new AnonymousClass3UU(anonymousClass3UV2.A("map", "amaro/map.png").A("overlay_map", "amaro/overlay_map.png").A("blackboard", "shared/blackboard.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 17;
            str = "Mayfair";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_mayfair;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "mayfair/border.png";
            sparseArray.put(17, new AnonymousClass3UU(anonymousClass3UV2.A("map", "mayfair/colorGradient.png").A("glowField", "mayfair/glowField.png").A("overlay", "mayfair/overlayMap100.png").A("colorOverlay", "mayfair/colorOverlay.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 23;
            str = "Rise";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_rise;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(23, new AnonymousClass3UU(anonymousClass3UV2.A("map", "rise/map.png").A("overlay_map", "shared/overlay_map.png").A("blackboard", "shared/blackboard.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 26;
            str = "Hudson";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_hudson;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "hudson/border.png";
            sparseArray.put(26, new AnonymousClass3UU(anonymousClass3UV2.A("map", "hudson/map.png").A("blowout", "hudson/blowout.pkm").A("overlay_map", "shared/overlay_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 25;
            str = "Valencia";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_valencia;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(25, new AnonymousClass3UU(anonymousClass3UV2.A("map", "valencia/map.png").A("gradient_map", "valencia/gradient_map.png")));
            anonymousClass3UV = new AnonymousClass3UV();
            anonymousClass3UV.f41622D = 1;
            anonymousClass3UV.f41623E = "X-Pro II";
            anonymousClass3UV.f41625G = C0164R.drawable.filter_xproii;
            anonymousClass3UV.f41626H = "XPro2";
            anonymousClass3UV.f41620B = "x_pro2/border.png";
            String str2 = "shared/vignette_map_plus_darker.png";
            sparseArray.put(1, new AnonymousClass3UU(anonymousClass3UV.A("map", "x_pro2/map.png").A("vignette_map_plus_darker", str2)));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 27;
            str = "Sierra";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_sierra;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "sierra/border.png";
            sparseArray.put(27, new AnonymousClass3UU(anonymousClass3UV2.A("map", "sierra/map.png").A("smoke", "sierra/smoke.png").A("vignette", "sierra/vignette.png").A("overlay_map", "amaro/overlay_map.png").A("soft_light", "sierra/soft_light.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 28;
            str = "Willow";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_willow;
            anonymousClass3UV2.f41626H = str;
            str = "map";
            sparseArray.put(28, new AnonymousClass3UU(anonymousClass3UV2.A("glowMap", "willow/glowField.png").A("overlayMap", "willow/overlayMap81.png").A("borderTexture", "willow/borderTexture.png").A("vignette", "willow/willowVignette.png").A("softLightMap", "willow/willowSoftLight100.png").A(str, "willow/willowMap.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 2;
            anonymousClass3UV2.f41623E = "Lo-Fi";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_lofi;
            anonymousClass3UV2.f41626H = "LoFi";
            anonymousClass3UV2.f41620B = "lo_fi/border.png";
            sparseArray.put(2, new AnonymousClass3UU(anonymousClass3UV2.A(str, "lo_fi/map.png").A("vignette_map", "lo_fi/vignette_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 3;
            str = "Earlybird";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_earlybird;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "earlybird/border.png";
            sparseArray.put(3, new AnonymousClass3UU(anonymousClass3UV2.A("map", "earlybird/earlybird_map.png").A("curves_map", "earlybird/curves_map.png").A("vignette_map_plus_darker", str2).A("overlay_map", "earlybird/overlay_map.png").A("blowout_map", "earlybird/blowout_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 22;
            str = "Brannan";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_brannan;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "brannan/border.png";
            sparseArray.put(22, new AnonymousClass3UU(anonymousClass3UV2.A("map", "brannan/map.png").A("luma_map", "brannan/luma_map.png").A("screen_map", "brannan/screen_map.png").A("blowout_map", "brannan/blowout_map.png").A("contrast_map", "brannan/contrast_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 10;
            str = "Inkwell";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_inkwell;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "shared/border_white.png";
            sparseArray.put(10, new AnonymousClass3UU(anonymousClass3UV2.A("map", "inkwell/map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 21;
            str = "Hefe";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_hefe;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "shared/border_black.png";
            sparseArray.put(21, new AnonymousClass3UU(anonymousClass3UV2.A("map", "hefe/map.png").A("metal", "hefe/metal.pkm").A("edge_burn", "shared/edge_burn.pkm").A("gradient_map", "hefe/gradient_map.png").A("soft_light_map", "hefe/soft_light_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 15;
            str = "Nashville";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_nashville;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "nashville/border.png";
            sparseArray.put(15, new AnonymousClass3UU(anonymousClass3UV2.A("map", "nashville/map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 18;
            str = "Sutro";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_sutro;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "shared/border_black.png";
            sparseArray.put(18, new AnonymousClass3UU(anonymousClass3UV2.A("map", "sutro/map.png").A("metal", "sutro/metal.pkm").A("edge_burn", "sutro/edge_burn.pkm").A("black_overlay_map", "shared/black_overlay_map.png").A("soft_light_map", "shared/soft_light_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 19;
            str = "Toaster";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_toaster;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "shared/border_white.png";
            sparseArray.put(19, new AnonymousClass3UU(anonymousClass3UV2.A("map", "toaster/map.png").A("metal", "toaster/metal.pkm").A("color_shift_map", "toaster/color_shift_map.png").A("overlay_map", "toaster/overlay_map.png").A("soft_light_map", "toaster/soft_light_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 20;
            str = "Walden";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_walden;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41620B = "shared/border_black.png";
            sparseArray.put(20, new AnonymousClass3UU(anonymousClass3UV2.A("map", "walden/map.png").A("vignette_map", "shared/vignette_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 14;
            anonymousClass3UV2.f41623E = "1977";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_1977;
            anonymousClass3UV2.f41626H = "Nineteen77";
            anonymousClass3UV2.f41620B = "shared/border_white.png";
            sparseArray.put(14, new AnonymousClass3UU(anonymousClass3UV2.A("map", "1977/map.png").A("screen_map", "1977/screen_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 16;
            anonymousClass3UV2.f41623E = "Kelvin";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_kelvin;
            anonymousClass3UV2.f41626H = "LordKelvin";
            anonymousClass3UV2.f41620B = "lord_kelvin/border.png";
            sparseArray.put(16, new AnonymousClass3UU(anonymousClass3UV2.A("map", "lord_kelvin/map.png")));
            AnonymousClass3UV anonymousClass3UV3 = new AnonymousClass3UV();
            anonymousClass3UV3.f41622D = -2;
            String str3 = "OES";
            anonymousClass3UV3.f41623E = str3;
            anonymousClass3UV3.f41626H = str3;
            sparseArray.put(-2, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV3 = new AnonymousClass3UV();
            anonymousClass3UV3.f41622D = -1;
            str3 = "YUV";
            anonymousClass3UV3.f41623E = str3;
            anonymousClass3UV3.f41626H = str3;
            sparseArray.put(-1, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 109;
            str = "Stinson";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_stinson;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(109, new AnonymousClass3UU(anonymousClass3UV2.A("map", "video/stinson/curves.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 106;
            str = "Vesper";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_vesper;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(106, new AnonymousClass3UU(anonymousClass3UV2.A("map", "video/vesper/map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 112;
            str = "Clarendon";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_clarendon;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(112, new AnonymousClass3UU(anonymousClass3UV2.A("map", "video/clarendon/Glacial1.png").A("map2", "video/clarendon/Glacial2.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 118;
            str = "Maven";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_maven;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(118, new AnonymousClass3UU(anonymousClass3UV2.A("map1", "video/maven/Lansdowne1.png").A("map2", "video/maven/Lansdowne2.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = ParserMinimalBase.INT_r;
            anonymousClass3UV2.f41623E = "Gingham";
            anonymousClass3UV2.f41624F = "Lagos";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_gingham;
            anonymousClass3UV2.f41626H = "Gingham";
            sparseArray.put(ParserMinimalBase.INT_r, new AnonymousClass3UU(anonymousClass3UV2.A("map", "video/gingham/curves1.png").A("mapLgg", "video/gingham/curves_lgg.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 107;
            str = "Ginza";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_ginza;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(107, new AnonymousClass3UU(anonymousClass3UV2.A("map1", "video/ginza/curves1.png").A("map2", "video/ginza/curves2.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 113;
            str = "Skyline";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_skyline;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(113, new AnonymousClass3UU(anonymousClass3UV2.A("map", "video/skyline/curves.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 105;
            str = "Dogpatch";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_dogpatch;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(105, new AnonymousClass3UU(anonymousClass3UV2.A("map1", "video/dogpatch/curves1.png").A("mapLgg", "video/dogpatch/curves_lgg.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 115;
            str = "Brooklyn";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_brooklyn;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(115, new AnonymousClass3UU(anonymousClass3UV2.A("map", "video/brooklyn/curves.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 111;
            str = "Moon";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_moon;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(111, new AnonymousClass3UU(anonymousClass3UV2.A("map1", "video/moon/curves1.png").A("map2", "video/moon/curves2.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = ParserMinimalBase.INT_u;
            str = "Helena";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_helena;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(ParserMinimalBase.INT_u, new AnonymousClass3UU(anonymousClass3UV2.A("map1", "video/helena/epic_1.png").A("map2", "video/helena/epic_2.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = ParserMinimalBase.INT_t;
            str = "Ashby";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_ashby;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(ParserMinimalBase.INT_t, new AnonymousClass3UU(anonymousClass3UV2.A("tonemap", "video/ashby/tonemap.png").A("levels", "video/ashby/levels.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 108;
            str = "Charmes";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_charmes;
            anonymousClass3UV2.f41626H = str;
            str = "map";
            sparseArray.put(108, new AnonymousClass3UU(anonymousClass3UV2.A(str, "video/charmes/map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 640;
            anonymousClass3UV2.f41623E = "BrightContrast";
            anonymousClass3UV2.f41624F = "Melbourne";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "StandardColorMap";
            sparseArray.put(640, new AnonymousClass3UU(anonymousClass3UV2.A(str, "brightcontrast/map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 642;
            anonymousClass3UV2.f41623E = "Crazy";
            anonymousClass3UV2.f41624F = "Rio de Janeiro";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "CrazyColor";
            sparseArray.put(642, new AnonymousClass3UU(anonymousClass3UV2.A(str, "crazycolor/map.png").A("overlay_map", "crazycolor/overlay_map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 643;
            anonymousClass3UV2.f41623E = "Subtle";
            anonymousClass3UV2.f41624F = "Oslo";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "StandardColorMap";
            sparseArray.put(643, new AnonymousClass3UU(anonymousClass3UV2.A("map", "subtlecolor/map.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 644;
            str = "Pixelated";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = str;
            sparseArray.put(644, new AnonymousClass3UU(anonymousClass3UV2));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 700;
            anonymousClass3UV2.f41623E = "TintYellow";
            anonymousClass3UV2.f41624F = "Lisbon";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_yellow.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(700, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 701;
            anonymousClass3UV2.f41624F = "Seoul";
            anonymousClass3UV2.f41623E = "TintBlue";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_blue.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(701, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 702;
            anonymousClass3UV2.f41623E = "DramaticBlackWhite";
            anonymousClass3UV2.f41624F = "Tokyo";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_bw.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(702, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 703;
            anonymousClass3UV2.f41623E = "CinemaRed";
            anonymousClass3UV2.f41624F = "Abu Dhabi";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_cinema_red.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(703, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 704;
            anonymousClass3UV2.f41623E = "CinemaGreen";
            anonymousClass3UV2.f41624F = "Mexico City";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_cinema_green.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(704, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 705;
            anonymousClass3UV2.f41623E = "CinemaBlue";
            anonymousClass3UV2.f41624F = "Buenos Aires";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_cinema_blue.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(705, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 706;
            anonymousClass3UV2.f41623E = "CrystalClear";
            anonymousClass3UV2.f41624F = "Jakarta";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_clear.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(706, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 707;
            anonymousClass3UV2.f41623E = "Vintage";
            anonymousClass3UV2.f41624F = "New York";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_vintage.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(707, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 708;
            anonymousClass3UV2.f41623E = "Instant";
            anonymousClass3UV2.f41624F = "Paris";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_instant.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(708, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 709;
            anonymousClass3UV2.f41623E = "PastelPink";
            anonymousClass3UV2.f41624F = "Jaipur";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_pastel_pink.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(709, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 710;
            anonymousClass3UV2.f41623E = "PastelSky";
            anonymousClass3UV2.f41624F = "Cairo";
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = "Tint";
            anonymousClass3UV3 = anonymousClass3UV2.A("uColorLut", "tint/clut_pastel_sky.png");
            anonymousClass3UV3.f41621C = AnonymousClass3UW.COLOR_FILTER;
            sparseArray.put(710, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV3 = new AnonymousClass3UV();
            anonymousClass3UV3.f41622D = 750;
            anonymousClass3UV3.f41623E = "EnhanceSoft";
            anonymousClass3UV3.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV3.f41626H = "Enhance";
            anonymousClass3UV3.f41621C = AnonymousClass3UW.ENHANCE_FILTER;
            sparseArray.put(750, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV3 = new AnonymousClass3UV();
            anonymousClass3UV3.f41622D = 751;
            anonymousClass3UV3.f41623E = "EnhanceSharp";
            anonymousClass3UV3.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV3.f41626H = "Enhance";
            anonymousClass3UV3.f41621C = AnonymousClass3UW.ENHANCE_FILTER;
            sparseArray.put(751, new AnonymousClass3UU(anonymousClass3UV3));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 752;
            str = "Enhance";
            anonymousClass3UV2.f41623E = str;
            anonymousClass3UV2.f41625G = C0164R.drawable.filter_normal;
            anonymousClass3UV2.f41626H = str;
            anonymousClass3UV2.f41621C = AnonymousClass3UW.ENHANCE_FILTER;
            sparseArray.put(752, new AnonymousClass3UU(anonymousClass3UV2));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 800;
            anonymousClass3UV2.f41623E = "CircleFrame";
            anonymousClass3UV2.f41626H = "ImageMaskWithOverlay";
            sparseArray.put(800, new AnonymousClass3UU(anonymousClass3UV2.A("image_mask", "image_mask/circle_mask.png").A("image_overlay", "image_overlay/circle_overlay.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 801;
            anonymousClass3UV2.f41623E = "FadeFrame";
            anonymousClass3UV2.f41626H = "ImageMask";
            str = "image_mask";
            sparseArray.put(801, new AnonymousClass3UU(anonymousClass3UV2.A(str, "image_mask/fade_mask.png")));
            anonymousClass3UV2 = new AnonymousClass3UV();
            anonymousClass3UV2.f41622D = 802;
            anonymousClass3UV2.f41623E = "SquareFrame";
            anonymousClass3UV2.f41626H = "ImageMaskWithOverlay";
            sparseArray.put(802, new AnonymousClass3UU(anonymousClass3UV2.A(str, "image_mask/square_mask.png").A("image_overlay", "image_overlay/square_overlay.png")));
        }
        return (AnonymousClass3UU) f68317B.get(i);
    }

    /* renamed from: C */
    public final String m28305C(int i) {
        return B(i).f41615E;
    }

    /* renamed from: D */
    public final String m28306D(int i) {
        return B(i).f41616F;
    }

    /* renamed from: E */
    public final AnonymousClass3UU m28307E() {
        return B(0);
    }
}
