package X;

/* renamed from: X.0x3 */
public enum AnonymousClass0x3 {
    ADS,
    ORGANIC_REPORT,
    ORGANIC_REPORT_SPAM,
    ORGANIC_SHOW_LESS,
    AD4AD,
    MAIN_FEED_ORGANIC_REPORT,
    MAIN_FEED_UNFOLLOW_USER,
    MAIN_FEED_UNFOLLOW_HASHTAG,
    MAIN_FEED_POST_RECS_HIDE_FROM_AUTHOR,
    UNRELATED_HASHTAG,
    NONE
}
