package X;

/* renamed from: X.08Z */
public enum AnonymousClass08Z {
    NOTIFICATION_RECEIVED,
    DUPLICATED_NOTIFICATION,
    DELIVERYHELPER_FAILED,
    DISCARDED_NOTIFICATION,
    ACKNOWLEDGED_NOTIFICATION,
    FAIL_NULL_NOTIF_ID,
    FAIL_INVALID_RECEIVER,
    FAIL_UNTRUSTED_APP,
    FAIL_SECURE_BROADCAST,
    REDELIVER_NOTIFICATION
}
